# Generated by Django 2.0 on 2018-04-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0002_auto_20180413_0611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxgroup',
            old_name='tax_max_per',
            new_name='tax_per',
        ),
    ]
