# Generated by Django 2.0 on 2018-04-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0003_auto_20180413_0612'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemtax',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemtax',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemtax',
            name='tax_name',
        ),
        migrations.AddField(
            model_name='item',
            name='tax_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ERP.TaxGroup'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemTax',
        ),
    ]
