# Generated by Django 2.0 on 2018-04-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0006_item_serial_no_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='serila_prefix',
            new_name='serial_prefix',
        ),
    ]
