# Generated by Django 2.0 on 2018-04-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0008_auto_20180417_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
