# Generated by Django 2.0 on 2018-04-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0010_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='series',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
